---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: debian-7.7
    driver:
        box: debianstandard_20150428_1258
        box_url: http://vagrantimages.yrdci.fra.hybris.com/debianstandard_20150428_1258.box
  - name: debian-8
    driver:
        box: debian/jessie64
        box_url: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.3.0/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[chef-dash::dash-prod]
      - recipe[chef-dash::repo]
    attributes: {}
    network:
    - ["forwarded_port", { guest: 80, host: 8080 }]
  - name: dash-scripts
    run_list:
      - recipe[chef-dash::dash-scripts]
    attributes: {}
