---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: false

platforms:
  - name: debian-8
    driver:
        box: debianstandard_20160202_1500
        box_url: http://vagrantimages.yrdci.fra.hybris.com/debianstandard_20160202_1500.box
        network:
        - ["forwarded_port", { guest: 80, host: 8080 }]

suites:
  - name: default
    run_list:
      - recipe[chef-dash::dash-prod]
      - recipe[chef-dash::repo]
    attributes: {}
  - name: dash-scripts
    run_list:
      - recipe[chef-dash::dash-scripts]
    attributes: {}
