Metrics/LineLength:
  Max: 200

Style/Encoding:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/UnneededPercentX:
  Enabled: false

Style/EndOfLine:
  Enabled: false

AllCops:
  Exclude:
    - Vagrantfile
    - Thorfile
    